### ISSUE TITLE
Provide CHANGELOG or release notes

### ISSUE THREAD

**Issue by medikoo** [elastic/require-in-the-middle#34]
It'll be great to have resource to learn on what changes were published.

It's especially helpful across major upgrades, currently (without inspecting the code changes) it's not clear what breaking changes were introduced with v5

**Comment by watson** [comment]
Good idea. In the meantime, we try to always follow the [conventional commits](https://www.conventionalcommits.org/) standard, so it's possible to read the commit messages leading up to a major version to see what is considered breaking. In the case of v5.0.0, it's this commit: https://github.com/elastic/require-in-the-middle/commit/3cc2833ed40148e2957253383db37b484f27d62c

The breaking change is that the API of the public `.cache` property changed with that commit. So if you never used the `cache` property you're all good.

**Comment by medikoo** [comment]
> Good idea. In the meantime, we try to always follow the conventional commits standard, 

If it's the case, then technically CHANGELOG generation can be automated (e.g. in `serverless` we generate releases via: https://github.com/serverless/serverless/blob/db4ff0b1cf62f371c610b31666c7872698b2bc77/package.json#L68 )

Anyway thanks for clarification on what changed

**Comment by trentm** [comment]
I've started a CHANGELOG.md starting with v5.1.0.
