### ISSUE TITLE
Use this module with bundled node modules (using webpack)

### ISSUE THREAD

**Issue by mruoss** [elastic/require-in-the-middle#35]
Hi there

I'm coming over from an issue on DataDog/dd-trace-js#827 where I figured out, the issue actually lies in this library.

We are using webpack to bundle our application and all the required node modules  in a single bundle. Now we installed [dd-trace-js](https://github.com/DataDog/dd-trace-js) which uses `require-in-the-middle` to hook up its plugins. However, for us the `require-in-the-middle` does not work if the node modules are bundled. Is this a know inssue? Is there a way to use `require-in-the-middle` with bundled node modules?

I worked around the issue using  [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) but I would prefer going back to including the node modules in the bundle.

Thanks,
Michael

**Comment by watson** [comment]
Correct, this module doesn't work if all your modules have been bundled into a single JavaScript file. This module works as a hook into the `require` function in Node.js. When the `require` function isn't used (as is the case when you bundle all your modules), the hook will never fire.

To my knowledge, there's no way to really support this feature and it's not a bug. Normally this is never an issue as bundling of Node.js modules on the server-side isn't recommended in general.

Can I ask what you hope to achieve by bundling all your modules into one file?

**Comment by mruoss** [comment]
I see, thanks for the clarification. We're using

**Comment by vitramir** [comment]
> reduce our (docker image) build time

Our team have the same reason. Reduce of final bundle size is also important for docker images and for lambdas.

@watson can you explain more detailed why do think it is impossible, please? 

Compiled file has `__webpack_require__` function. I think we can replace it the same way you replace `require`

**Comment by watson** [comment]
@vitramir I didn't know about `__webpack_require__`. If it's possible somehow to hook into that, then it might be possible to make this module work for this scenario as well. I don't have any time currently to dive into this, unfortunately, but if any of you like to take a crack at it, I'd be happy to review ☺️

**Comment by skanygin** [comment]
@watson @vitramir @mruoss I made a research and found that it is impossible to implement inside the library. [Here](https://github.com/googleapis/cloud-trace-nodejs/issues/774#issuecomment-462582791) the guys from Google mentioned similar results  and [explains why](https://github.com/googleapis/cloud-trace-nodejs/issues/774#issuecomment-515238260). Google's library built on TypeScript but uses in common the same mechanism. The only way to add support for webpack is to create a plugin that wraps exports or `__webpack_require__`.

**Comment by vitramir** [comment]
@skanygin They only mentioned that it is impossible to support webpack with the same approach. Yes, I am also talking about some kind of plugin.

In transpiled file all `require` statements replaced with `__webpack_require__`. At some point of execution `require-in-the-middle` will try to replace default `require`. We need to replace `__webpack_require__` here, instead of default `require`. I made it work. My next issue is that webpack uses numeric indices as input to `__webpack_require__`, but `require-in-the-middle` needs package name. So, it executes for every `require`, but doesn’t inject any code. My next step will be to find a way to map webpack indices back to packages names/paths.

**Comment by vitramir** [comment]
I finished the first prototype of webpack plugin. This seems to work for my case. 

https://github.com/vitramir/require-in-the-middle-webpack-example

There are 3 main steps:
1. Collect paths of modules  
2. Update webpack runtime code
3. Update `require-in-the-middle` source code

All steps are commented in code.

@watson Can you advise something about changes in `require-in-the-middle` sources, please:
https://github.com/vitramir/require-in-the-middle-webpack-example/blob/master/webpack.config.js#L112-L167

I don't like to make them by plugin.

**Comment by techmunk** [comment]
For anyone interested in this, I've written a Webpack Plugin that can do this WITHOUT needing to patch or change code in require-in-the-middle.

What follows is typescript code, so make changes as needed for JS.

```ts
import { relative, sep } from 'path'
import { compilation, Compiler } from 'webpack'

declare class CompilationModule extends compilation.Module {
  resource?: string
  external?: boolean
}

export class WebpackRequireInTheMiddlePlugin {
  public readonly name = 'WebpackRequireInTheMiddlePlugin'
  protected readonly modulesMap: Map<number | string | null, string>
  protected readonly modules: string[]

  public constructor(modules?: string[]) {
    this.modulesMap = new Map()
    this.modules = modules ?? []
  }

  public apply(compiler: Compiler): void {
    compiler.hooks.compilation.tap(this.name, compilation => this.compilation(compilation))
  }

  protected compilation(compilation: compilation.Compilation): void {
    compilation.hooks.afterOptimizeModuleIds.tap(this.name, modules => this.mapModuleIds(modules))
    compilation.mainTemplate.hooks.localVars.tap(this.name, (source) => this.addLocalVarSources(source))
    compilation.mainTemplate.hooks.require.tap(this.name, (source) => this.addRequireSources(source))
  }

  protected getModuleName(filename?: string): string {
    if (filename) {
      const segments = filename.split(sep)
      const index = segments.lastIndexOf('node_modules')
      if (index !== -1 && segments[index + 1]) {
        return segments[index + 1][0] === '@' ? `${segments[index + 1]}/${segments[index + 2]}` : segments[index + 1]
      }
    }

    return ''
  }

  protected includeModule(module: CompilationModule): boolean {
    const moduleName = this.getModuleName(module.resource)
    return this.modules.length === 0 || (moduleName !== '' && this.modules.includes(moduleName))
  }

  protected mapModuleIds(modules: CompilationModule[]): void {
    for (const module of modules) {
      if (!module.external && module.resource && this.includeModule(module)) {
        this.modulesMap.set(module.id, relative(process.cwd(), module.resource))
      }
    }
  }

  protected addLocalVarSources(source: string): string {
    return `${source}
const { sep } = require('path')
const __ritm_modules_map__ = new Map(${JSON.stringify(Array.from(this.modulesMap.entries()), null, 2)})
const __ritm_Module__ = module.require('module')
const __ritm_require__ = __ritm_Module__.prototype.require
const __ritm_require_shim__ = function (id) {return modules[id] ? __webpack_require__(id) : __ritm_require__(id)}
__ritm_Module__.prototype.require = __ritm_require_shim__
const __ritm_resolve_filename__ = __ritm_Module__._resolveFilename
__ritm_Module__._resolveFilename = function (id) {
  if (modules[id] && __ritm_modules_map__.has(id)) {return \`\${process.cwd()}\${sep}\${__ritm_modules_map__.get(id)}\`}
  return __ritm_resolve_filename__.apply(this, arguments)
}
const __ritm_shimmed__ = {}
`
  }

  protected addRequireSources(source: string): string {
    return `
if (__ritm_Module__.prototype.require !== __ritm_require_shim__ && !__ritm_shimmed__[moduleId]) {
  __ritm_shimmed__[moduleId] = true
  if (__ritm_modules_map__.has(moduleId)) {
    const exports = __ritm_Module__.prototype.require(moduleId)
    installedModules[moduleId].exports = exports
  }
}
${source}`
  }
}
```

To use:

```ts
    const modules = [
      'apollo-server-core',
      'bluebird',
      'cassandra-driver',
      'elasticsearch',
      'express',
      'express-graphql',
      'express-queue',
      'fastify',
      'finalhandler',
      'generic-pool',
      'graphql',
      'handlebars',
      'hapi',
      '@hapi/hapi',
      'http',
      'https',
      'http2',
      'ioredis',
      'jade',
      'knex',
      'koa',
      'koa-router',
      '@koa/router',
      'memcached',
      'mimic-response',
      'mongodb-core',
      'mongodb',
      'mysql',
      'mysql2',
      'pg',
      'pug',
      'redis',
      'restify',
      'tedious',
      'ws'
    ]

this.config.plugins?.push(new WebpackRequireInTheMiddlePlugin(modules))
```
The list of modules above is taken straight from elastic-apm-node. If elastic-apm-node exported the modules, would probably not even need that!

This is tested against webpack 4 with an effort to get elastic-apm-node to work with a full bundled webpack build.

**Comment by techmunk** [comment]
I should also point out that the entry looks like the following:

```ts
{ server: ['source-map-support/register', 'elastic-apm-node/start', './index'] }
```

We configure elastic APM via environment variables.
```

**Comment by techmunk** [comment]
I had not properly tested when using a built bundle in a directory without node_modules. I've updated my comment above with a version that will work when there is no node_modules directory present. Part of the plugin is really only for supporting elastic-apm-nodejs.

**Comment by knvpk** [comment]
Hi @vitramir , do you still using the code snippet you provided, actually im facing the same issue with opentelemetry(which uses require-in-the-middle) so i added your snippet and im getting the error that `compilation.hooks.succeedModule.tap is deprecated.`

**Comment by knvpk** [comment]
Hi @techmunk , i did also checked with your solution but im getting "modules not defiend",

**Comment by tlhunter** [comment]
I suspect @techmunk's solution in https://github.com/elastic/require-in-the-middle/issues/35#issuecomment-710807619 might have been written for Webpack v4 due to the incompatibility with today's Webpack (or possibly it relied upon non-public variables). I, too, am unable to get it to work anymore.

**Comment by sibelius** [comment]
does anybody have a version of this for webpack 5 ?
