### ISSUE TITLE
Indentation with EsLint and Prettier

### ISSUE THREAD

**Issue by robertosousa1** [elastic/require-in-the-middle#46]
Is implementing a standard indentation for the project used Eslint and Prettier seen as interesting?

**Comment by astorm** [comment]
We're currently using [standardjs](https://standardjs.com/) as the code linter for the Elastic Node Agent and Node Agent adjacent projects.   You can run this linter via

    npm run lint
    
Developing different standards via Eslint and Prettier aren't on our radar _at this time_ -- but we may revisit this in the future.

**Comment by robertosousa1** [comment]
I understand. Thanks!!!
