### ISSUE TITLE
require-in-the-middle does not work when using request-promise & request-promise-native

### ISSUE THREAD

**Issue by kirrg001** [elastic/require-in-the-middle#61]
Hi there!

I am running into an error when requiring `request-promise` & `request-promise-native`.

The `request` module is used by `request-promise` and `request-promise-native`. But `require-in-the-middle` returns a patched copy of `request`, which makes it impossible to require `request-promise-native`.

See https://github.com/request/request-promise-native/blob/master/lib/rp.js#L7
See https://github.com/request/request-promise/blob/master/lib/rp.js#L10

Although `request` is deprecated, I think this is a general problem with `require-in-the-middle` when using two libraries, which need a fresh copy of a module.

I have attached a zip, which reproduces the error.

Regards,
Kate

[reproduce.zip](https://github.com/elastic/require-in-the-middle/files/10880312/reproduce.zip)

**Comment by kirrg001** [comment]
One option to solve this: instead of returning [the cached entry](https://github.com/elastic/require-in-the-middle/blob/main/index.js#L104), you could return the [original export](https://github.com/elastic/require-in-the-middle/blob/main/index.js#L114).

You just need to move this line above the cache check:
> const exports = self._origRequire.apply(this, arguments)

The cache has the role of ensuring that a package is not patched twice.

As the implementation of Node.js `Module.prototype.require` (=== `Module._load`) has it's own internal cache, it doesn't matter if you call the original require or not - [see](https://github.com/bmeck/node/blob/master/lib/internal/modules/cjs/loader.js#L791).

**Comment by trentm** [comment]
@kirrg001 Sorry for the delay. I've created a PR that fixes this -- at least for the cases that I see, including your "reproduce.zip". Thanks very much for that.
